import { createContext, useContext, useMemo, useState, type ReactNode } from "react";
import type { Language } from "./types";

const sv = {
  searchPlaceholder:"Sök titel, författare, ISBN eller ASIN", advanced:"Avancerat", scanBook:"Skanna en bok", scanBarcode:"ISBN eller streckkod med kameran", scanText:"Skanna ISBN/ASIN som text", scanScreen:"Läs av koden från en läsplatta eller skärm", manualCode:"Du kan också skriva ISBN eller ASIN direkt i sökfältet.",
  readThisYear:"Böcker jag läst i år", booksInLibrary:"böcker i biblioteket", bookInLibrary:"bok i biblioteket", collection:"DIN SAMLING", library:"Mitt bibliotek", searchResults:"SÖKRESULTAT", searching:"Söker…", hits:"träffar", noBooks:"Här är det tomt än", noBooksHelp:"Sök efter en bok och lägg till den.", previous:"Föregående", next:"Nästa", page:"Sida", unknownYear:"Utgivningsår saknas", pages:"sidor", favorite:"Favorit",
  home:"Startsida", statistics:"Statistik", settings:"Inställningar", signOut:"Logga ut", customize:"ANPASSA", theme:"Tema", themeHelp:"Välj hur SunBooks ska se ut.", system:"Följ enheten", light:"Ljust beige", dark:"Mörkgrått", account:"Konto", googleAccount:"Google-konto", language:"Språk", languageHelp:"Sidan byter språk direkt.", swedish:"Svenska", english:"English",
  yearMissing:"År saknas", isbn:"ISBN", languageShort:"språk", about:"Om boken", noDescription:"Ingen beskrivning finns tillgänglig för den här boken.", categories:"Kategorier", noCategories:"Inga kategorier angivna för den här boken.", readingStatus:"Lässtatus", statusHelp:"Välj var du befinner dig med boken.", wantToRead:"Vill läsa", reading:"Läser", read:"Läst", dnf:"DNF", dnfForNow:"DNF for now",
  ownedAs:"Jag äger den som", chooseMultiple:"Välj en eller flera.", physical:"Fysisk bok", ebook:"E-bok", audio:"Ljudbok", addFavorite:"Lägg till som favorit", remove:"Ta bort", removeBook:"Ta bort boken?", removeConfirm:"Boken och dina privata anteckningar tas bort.", cancel:"Avbryt", confirmRemove:"Ja, ta bort",
  saved:"Sparad", saving:"Sparar…", privateReview:"Min recension", reviewPlaceholder:"Skriv vad du tyckte om boken…", reviewPrivate:"Bara du kan se recensionen.", myRating:"Mitt betyg", noRating:"Inget betyg", bajs:"BAJS", progress:"Läsprogress", progressPages:"Sida", progressPercent:"Procent", started:"Påbörjad", finished:"Avslutad", startNew:"Starta ny läsning", clearProgress:"Ta bort progress",
  copies:"Mina exemplar", addCopy:"Lägg till exemplar", provider:"Tjänst eller butik", device:"Läsplatta/enhet", note:"Anteckning", tags:"Egna etiketter", addTag:"Lägg till etikett", added:"Tillagd", latestRead:"Senaste läsningen", removeLatest:"Ta bort senaste",
  filters:"Filter och sortering", allStatuses:"Alla statusar", allFormats:"Alla format", allGenres:"Alla genrer", allLanguages:"Alla språk", fromYear:"Från år", toYear:"Till år", minPages:"Min sidor", maxPages:"Max sidor", sortRecent:"Senast tillagd", sortTitle:"Titel", sortAuthor:"Författare", sortYear:"Utgivningsår", sortPages:"Antal sidor", favoritesOnly:"Bara favoriter", clearFilters:"Rensa filter", results:"resultat",
  statsTitle:"Din läsning", totalOwned:"Böcker du äger", completed:"Avslutade", currentlyReading:"Läser just nu", pagesRead:"Lästa sidor", formats:"Format", statuses:"Statusar", ratings:"Dina betyg", noStats:"Statistiken växer när du använder SunBooks.",
  exportData:"Exportera mina data", exportHelp:"Ladda ner en privat säkerhetskopia som JSON.", importData:"Importera säkerhetskopia", importHelp:"Återställ böcker från en SunBooks-fil.", deleteData:"Radera biblioteket", deleteDataHelp:"Tar bort alla dina sparade böcker från SunBooks.", deleteLibraryConfirm:"Radera hela biblioteket?", deleteLibraryWarning:"Detta går inte att ångra.", deleteAccount:"Radera konto", deleteAccountHelp:"Tar bort biblioteket och ditt SunBooks-konto.", deleteAccountConfirm:"Radera kontot permanent?", confirmDelete:"Ja, radera",
  loginTagline:"Din egen bokhylla, alltid nära.", continueGoogle:"Fortsätt med Google", privateData:"Dina böcker sparas privat på ditt konto.", openMenu:"Öppna meny", close:"Stäng", coverOf:"Omslag till", scanCode:"Rikta kameran mot streckkoden", scanAuto:"Skanningen sker automatiskt", scanTextFrame:"Placera ASIN- eller ISBN-texten i rutan", scanTextHelp:"Håll telefonen stilla och tryck på knappen", readText:"Läs av texten", readingText:"Läser text…",
};

const en: typeof sv = {
  searchPlaceholder:"Search title, author, ISBN or ASIN", advanced:"Advanced", scanBook:"Scan a book", scanBarcode:"ISBN or barcode with the camera", scanText:"Scan ISBN/ASIN as text", scanScreen:"Read the code from an e-reader or screen", manualCode:"You can also type an ISBN or ASIN directly in the search field.",
  readThisYear:"Books I read this year", booksInLibrary:"books in the library", bookInLibrary:"book in the library", collection:"YOUR COLLECTION", library:"My library", searchResults:"SEARCH RESULTS", searching:"Searching…", hits:"matches", noBooks:"Nothing here yet", noBooksHelp:"Search for a book and add it.", previous:"Previous", next:"Next", page:"Page", unknownYear:"Publication year missing", pages:"pages", favorite:"Favorite",
  home:"Home", statistics:"Statistics", settings:"Settings", signOut:"Sign out", customize:"CUSTOMIZE", theme:"Theme", themeHelp:"Choose how SunBooks should look.", system:"Use device setting", light:"Light beige", dark:"Dark gray", account:"Account", googleAccount:"Google account", language:"Language", languageHelp:"The page changes language immediately.", swedish:"Svenska", english:"English",
  yearMissing:"Year missing", isbn:"ISBN", languageShort:"language", about:"About the book", noDescription:"No description is available for this book.", categories:"Categories", noCategories:"No categories are listed for this book.", readingStatus:"Reading status", statusHelp:"Choose where you are with the book.", wantToRead:"Want to read", reading:"Reading", read:"Read", dnf:"DNF", dnfForNow:"DNF for now",
  ownedAs:"I own it as", chooseMultiple:"Choose one or more.", physical:"Physical book", ebook:"E-book", audio:"Audiobook", addFavorite:"Add as favorite", remove:"Remove", removeBook:"Remove the book?", removeConfirm:"The book and your private notes will be removed.", cancel:"Cancel", confirmRemove:"Yes, remove",
  saved:"Saved", saving:"Saving…", privateReview:"My review", reviewPlaceholder:"Write what you thought about the book…", reviewPrivate:"Only you can see this review.", myRating:"My rating", noRating:"No rating", bajs:"POOP", progress:"Reading progress", progressPages:"Page", progressPercent:"Percent", started:"Started", finished:"Finished", startNew:"Start a new read", clearProgress:"Clear progress",
  copies:"My copies", addCopy:"Add copy", provider:"Service or store", device:"E-reader/device", note:"Note", tags:"My tags", addTag:"Add tag", added:"Added", latestRead:"Latest read", removeLatest:"Remove latest",
  filters:"Filters and sorting", allStatuses:"All statuses", allFormats:"All formats", allGenres:"All genres", allLanguages:"All languages", fromYear:"From year", toYear:"To year", minPages:"Min pages", maxPages:"Max pages", sortRecent:"Recently added", sortTitle:"Title", sortAuthor:"Author", sortYear:"Publication year", sortPages:"Page count", favoritesOnly:"Favorites only", clearFilters:"Clear filters", results:"results",
  statsTitle:"Your reading", totalOwned:"Books you own", completed:"Completed", currentlyReading:"Currently reading", pagesRead:"Pages read", formats:"Formats", statuses:"Statuses", ratings:"Your ratings", noStats:"Your statistics will grow as you use SunBooks.",
  exportData:"Export my data", exportHelp:"Download a private JSON backup.", importData:"Import backup", importHelp:"Restore books from a SunBooks file.", deleteData:"Delete library", deleteDataHelp:"Removes all your saved books from SunBooks.", deleteLibraryConfirm:"Delete the entire library?", deleteLibraryWarning:"This cannot be undone.", deleteAccount:"Delete account", deleteAccountHelp:"Removes the library and your SunBooks account.", deleteAccountConfirm:"Delete the account permanently?", confirmDelete:"Yes, delete",
  loginTagline:"Your own bookshelf, always close.", continueGoogle:"Continue with Google", privateData:"Your books are stored privately in your account.", openMenu:"Open menu", close:"Close", coverOf:"Cover of", scanCode:"Point the camera at the barcode", scanAuto:"Scanning is automatic", scanTextFrame:"Place the ASIN or ISBN text in the frame", scanTextHelp:"Hold the phone still and press the button", readText:"Read text", readingText:"Reading text…",
};

type Key = keyof typeof sv;
type I18nValue = { language: Language; setLanguage: (language: Language) => void; t: (key: Key) => string };
const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, updateLanguage] = useState<Language>(() => (localStorage.getItem("sunbooks-language") as Language) || "sv");
  const setLanguage = (next: Language) => { updateLanguage(next); localStorage.setItem("sunbooks-language", next); document.documentElement.lang = next; };
  const value = useMemo(() => ({ language, setLanguage, t: (key: Key) => (language === "sv" ? sv : en)[key] }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error("I18nProvider missing"); return value; }
