import { useMemo, useState } from "react";
import { BookOpen, Compass, Eye, EyeOff, Star } from "lucide-react";
import type { Book } from "../types";
import { useI18n } from "../i18n";

type Props={entries:Book[];loading:boolean;onSelect:(book:Book)=>void};

export function DiscoverPage({entries,loading,onSelect}:Props){
  const{t}=useI18n();const[term,setTerm]=useState("");const[genre,setGenre]=useState("all");const[scope,setScope]=useState("all");const[showSpoilers,setShowSpoilers]=useState(()=>localStorage.getItem("sunbooks-spoilers")==="true");
  const genres=useMemo(()=>Array.from(new Set(entries.flatMap(book=>book.genres||[]))).sort().slice(0,80),[entries]);
  const books=useMemo(()=>{const map=new Map<string,{book:Book;count:number;ratings:number[]}>();entries.forEach(book=>{if(scope==="owned"&&book.owned===false)return;if(scope==="read"&&book.readingStatus!=="read")return;if(genre!=="all"&&!book.genres?.includes(genre))return;if(term&&!`${book.title} ${book.authors.join(" ")}`.toLocaleLowerCase().includes(term.toLocaleLowerCase()))return;const item=map.get(book.id)||{book,count:0,ratings:[]};item.count++;if(typeof book.rating==="number")item.ratings.push(book.rating);map.set(book.id,item)});return Array.from(map.values()).sort((a,b)=>{const ar=a.ratings.length?a.ratings.reduce((x,y)=>x+y,0)/a.ratings.length:0;const br=b.ratings.length?b.ratings.reduce((x,y)=>x+y,0)/b.ratings.length:0;return br-ar||b.count-a.count})},[entries,term,genre,scope]);
  function spoilers(next:boolean){setShowSpoilers(next);localStorage.setItem("sunbooks-spoilers",String(next))}
  return <section className="content discover-page"><div className="content-heading"><div><p>{t("discover")}</p><h1>{t("discoverTitle")}</h1></div><Compass/></div><p className="discover-intro">{t("discoverIntro")}</p><div className="discover-filters"><input value={term} onChange={e=>setTerm(e.target.value)} placeholder={t("searchPlaceholder")}/><select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">{t("allBooks")}</option><option value="owned">{t("totalOwned")}</option><option value="read">{t("read")}</option></select><select value={genre} onChange={e=>setGenre(e.target.value)}><option value="all">{t("allGenres")}</option>{genres.map(value=><option key={value}>{value}</option>)}</select></div><div className="section-title-row"><h2>{t("highestRated")}</h2><button onClick={()=>spoilers(!showSpoilers)}>{showSpoilers?<EyeOff/>:<Eye/>}{showSpoilers?t("hideSpoilers"):t("showSpoilers")}</button></div>{loading?<div className="loader"/>:books.length===0?<div className="empty"><BookOpen/><h2>{t("noCommunity")}</h2></div>:<div className="discover-grid">{books.slice(0,20).map(({book,count,ratings})=>{const average=ratings.length?ratings.reduce((a,b)=>a+b,0)/ratings.length:null;const reviews=entries.filter(item=>item.id===book.id&&item.reviewPublic&&item.review);return <article className="discover-card" key={book.id}><button className="discover-book" onClick={()=>onSelect(book)}>{book.cover?<img src={book.cover} alt=""/>:<BookOpen/>}<span><strong>{book.title}</strong><small>{book.authors.join(", ")}</small>{average!==null&&<b><Star fill="currentColor"/>{average.toFixed(2)} · {ratings.length}</b>}<em>{count} {t("results")}</em></span></button>{reviews.map((review,index)=><div className="public-review" key={index}>{review.reviewSpoiler&&!showSpoilers?<div className="spoiler-mask"><strong>{t("spoilerWarning")}</strong><button onClick={()=>spoilers(true)}>{t("showAnyway")}</button></div>:<><b>{typeof review.rating==="number"?`${review.rating.toFixed(2)} ★`:""}</b><p>{review.review}</p></>}</div>)}</article>})}</div>}</section>
}
